### PR TITLE
Platformer Base Created

### PR DESCRIPTION
**Pull request by MTM828**
Created some important classes and a little physics. I'm not sure if there are any bugs though.
Also, shold I change this into a draft pull request?

### CODE REVIEW

**Comment by sparshg** [comment]
let me see, to test the code I can do `git checkout myBranch` instead of copying things. Also here there are 3 ways to merge,
#### The default merge:
Say you made 10 commits for this, and when you merge those 10 commits will be added to main branch
#### Squash and merge
This will squash those 10 commits into a single commit and merge, this will keep `git log` cleaner. **So I prefer this**
#### Rebase and merge
Rebase this branch with the main one and then commit

**Comment by MTM828** [comment]
Squash and merge it is, then.

**Comment by sparshg** [comment]
lol no, I didn't even review lol

**Comment by MTM828** [comment]
😅

**Pull request merged**
