### PR TITLE
Space_Invader

### PR DESCRIPTION
**Pull request by Sanchita1304**

### CODE REVIEW

**Comment by sparshg** [comment]
Hi, thanks for the contribution, unfortunately your game is showing error on launch:
```
pygame 2.1.2 (SDL 2.0.18, Python 3.9.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/Users/sparsh/Code/python/py-games/src/space_invader/main.py", line 17, in <module>
    BULLET_HIT_SOUND = pygame.mixer.Sound('Assets/Grenade+1.mp3')
FileNotFoundError: No file 'Assets/Grenade+1.mp3' found in working directory '/Users/sparsh/Code/python/py-games/src/space_invader'.
```

You can push your fixing commit on the same branch and it should update this PR as well.

**Comment by Sanchita1304** [comment]
Can i make another pull request and i will update everything of this game

**Comment by sparshg** [comment]
As you wish but you can update without making new one too

**Comment by Sanchita1304** [comment]
Actually this is my first time doing this so I don't know how to update this.

**Pull request closed without merging**
