### PR TITLE
Added Gifs

### PR DESCRIPTION
**Pull request by prjailani**
Added Game GIFs. Resolved Issue #27 .

### CODE REVIEW

**Comment by sparshg** [comment]
Can you increase the FPS of gifs?

**Comment by prjailani** [comment]
Yes will do in few hours. It's raining here.

**Comment by sparshg** [comment]
You can take a look at #46 in which image bot is used to reduce the size of gifs btw

**Comment by sparshg** [comment]
Are you still working on it?

**Pull request merged**
