### PR TITLE
added Number Game

### PR DESCRIPTION
**Pull request by R0merol**
added Number Game to the list of games

### CODE REVIEW

**Comment by R0merol** [comment]
I may have forgotten to update the branch somehow before merging this. Actually, Idk what the hell happened but this PR looks like a mess now, sorry

**Comment by sparshg** [comment]
Its okay I just rebased the master, I will fix it on merge

**Comment by sparshg** [comment]
Thanks for the contribution!

**Comment by R0merol** [comment]
Don't forget to add hacktoberfest-accepted label. Thanks <33

**Pull request merged**
