### PR TITLE
Added rock paper scissors game

### PR DESCRIPTION
**Pull request by MishaAkram**

### CODE REVIEW

**Comment by sparshg** [comment]
uhm two player rock paper scissor doesn't make sense as you can see what player 1 chose already. It would be better if we can play against computer instead.

**Comment by MishaAkram** [comment]
player 2 is actually computer that randomly selects between rock paper and scissors

**Comment by sparshg** [comment]
It seems really confusing, it doesn't select what I click?

https://user-images.githubusercontent.com/43041139/196485419-4135ae7e-15fb-43f4-baf4-9a78c09cbec5.mp4

**Comment by MishaAkram** [comment]
for now, it doesn't have a feature to play continuously, you have to load the game again to play

**Comment by MishaAkram** [comment]
Ok, I'll try to fix these issue that you seem to be experiencing.

**Comment by MishaAkram** [comment]
Hey, I have tried to fix the issues you mentioned earlier and added the feature to play again.
Please merge my PR, and assign it under Hacktoberfest 2022, Thanks.

**Comment by sparshg** [comment]
Thanks, much better now.

**Pull request merged**
