### PR TITLE
Physics improvements

### PR DESCRIPTION
**Pull request by sparshg**
Physics system now more stable

Moved clock to Physics... clock.tick(FPS) returns the time between previous and current frame.
Multiplied dt when updating velocities and positions
Added onGround for player
Improved wall collision, friction
When on ground, the y velocity used to float between two values, fixed that

I calculated the new values for gravity, jumpHeight etc. to work same as it was before adding dt
(multiply velocities by FPS, and accelerations by FPS\*FPS...
Example gravity was 0.5, which is now 0.5\*60\*60=1800)

### CODE REVIEW

**Review by MTM828 — APPROVED** [review]

**Comment by MTM828** [comment]
*Deletes "test.py" where he was playing about with dt*
Merge?

**Comment by MTM828** [comment]
@sparshg So... what's next?

**Comment by sparshg** [comment]
idk lol, any ideas?

**Comment by MTM828** [comment]
Uum... a pong game perhaps?

**Comment by MTM828** [comment]
We can do something else if you wish.

**Comment by sparshg** [comment]
sure, we can do that

**Comment by MTM828** [comment]
Oh yeah, that sounds like a better idea! (A much much better idea lol.)
So, what exactly are we going to make? The solar system or like bouncing balls or something?

**Comment by sparshg** [comment]
maybe like a game where you have to reach a goal using gravitational pull of planets, this is going to be so ambitious project, idk to do this or not lol, but first of all for that we need to implement gravity, so that every planet on screen experiences gravity due to every other object

**Comment by MTM828** [comment]
Oh so there are a bunch of magnets on the screen (which are the planets) and a ball (the player) uses their gravitational force to reach a certain coordinate and then they win, right?

**Comment by sparshg** [comment]
yeahh

**Comment by MTM828** [comment]
OK then, I'll start working on the base.

**Comment by sparshg** [comment]
I already have made the base file

**Pull request merged**
