### PR TITLE
Gravity Game Physics

### PR DESCRIPTION
**Pull request by MTM828**

### CODE REVIEW

**Comment by sparshg** [comment]
you can test my PR by simply doing `git checkout gravitybase` and run `python main.py` (or you can you github desktop client for gui https://desktop.github.com/

**Comment by sparshg** [comment]
btw I have used the [law of gravitation](https://energywavetheory.com/equations/fgmmr2/) to implement gravity and I am happy to say that it works perfectly, I calculated the speed at which the two planets should trace a circle, (using what I am taught in school, you will probably study gravity in higher classes) and it worked lol.

**Comment by MTM828** [comment]
Lol, I should've used that instead of creating my own physics engine.

**Comment by sparshg** [comment]
wow, you did really well considering you didn't know about that newton's law of gravitation. You actually made up your almost correct formula. Just had to do (dist * dist * Physics.gravity) instead of (dist * Physics.gravity). I have applied this formula in my PR but using vectors which is why I don't have to use atan, cos, sin which makes it more effiecent. Good Job!

**Comment by MTM828** [comment]
Thx. 😃😁

**Comment by sparshg** [comment]
You should try using vectors instead if possible while dealing with physics in future as they are much more easier to deal with once you know

**Pull request closed without merging**
