### PR TITLE
Added level editor and scrolling to platformer + improvements

### PR DESCRIPTION
**Pull request by MTM828**
Added a level editor, added a live background, added scrolling, split files a bit more, and played a bit with the colours.
And yes, I did remember to format my code after writing it. 😁 I also tried to add more comments.
Here's how it looks now:
screenshot
screenshot_2
Tried to give it a little more life.
And.. um.. sorry for making you wait for.. half a year.. hehe... 🙁

The platformer could use some more blocks and the editor has some bugs... I'll fix them in the upcoming pull request.

### CODE REVIEW

**Comment by MTM828** [comment]
Sometimes I get cyclic imports when splitting files, how do I stop that? Any clue? And also, the `IndexOutOfRange` error in the editor is literally **KILLING MEEEEEE**. Ehm, sorry obout that lol.

**Comment by sparshg** [comment]
lol it will take a bit to review, it would have been easier to review if you broke it into more commits

**Comment by MTM828** [comment]
Sry lol.

**Comment by sparshg** [comment]
I separated the classes a bit, will try to improve structure more before merging.
Great work btw

**Comment by sparshg** [comment]
Where are you getting `IndexOutOfRange` error?

**Comment by MTM828** [comment]
> I separated the classes a bit, will try to improve structure more before merging.
> Great work btw :)

Thanks.

> Where are you getting `IndexOutOfRange` error?

Level editor, when placing blocks (`SelectedBlock.place_block(self)`) past the bottom/top edge of the map, it tries to extend the world by adding one extra layer of air and a single ground block,  but fails.
And also, it reads negative coordinates as positive ones for some reason.

**Pull request merged**
