### PR TITLE
Adding keyboard functionality

### PR DESCRIPTION
**Pull request by MTM828**
Adding the key physics to the game.
I've Used velocities rather than instant movement (<del>`Player.x += 1`</del>) so the physics are smoother.
I've also made most of the classes (all of them but the `Main` and `Platform` classes) actual classes rather than using a variable to store them as objects, like what you did with the `Physics` class.

### CODE REVIEW

**Comment by sparshg** [comment]
no no no... You cannot make the other classes like the one I did with Physics... It was a special case because we shouldn't need to have an object to calculate say distance between two points or whatever, thats why its called static class that had static method (which do not need object). But in the case of Platforms, Main, Player, we are going to instantiate an object

**Comment by MTM828** [comment]
😓😂

**Comment by sparshg** [comment]
Also after a PR is merged, open a new branch instead of working on the same branch... See the old commits are also showing here

**Comment by MTM828** [comment]
Is this good?

**Comment by MTM828** [comment]
I think I commited on the `main` branch... 😐

**Comment by sparshg** [comment]
lol, plz make new branch after merging.. There are so many conflicts now.
nvm I will fix main and open new PR fkr these changes on new vranch

**Pull request closed without merging**
