### PR TITLE
Create block_breaker.py

### PR DESCRIPTION
**Pull request by YashIndane**
Added classic block breaker game

### CODE REVIEW

**Comment by sparshg** [comment]
Not working...
```
Traceback (most recent call last):
  File "/Users/sparsh/Code/python/py-games/src/block_breaker/block_breaker.py", line 19, in <module>
    sound=pygame.mixer.Sound("mario.wav")
FileNotFoundError: No file 'mario.wav' found in working directory '/Users/sparsh/Code/python/py-games/src/block_breaker'.
```

**Comment by YashIndane** [comment]
Ok I will add all files and create a new PR

**Comment by sparshg** [comment]
You should update this PR instead of creating new one.

**Comment by YashIndane** [comment]
Updated  PR

**Comment by sparshg** [comment]
Thanks for the contribution, here are some issues that needs to be solved before I can merge it though
- The block sometimes doesn't collide with blue ones as you can see below
- It just crashes when game is over
- Blue blocks overlap a lot and everything seems crowded
- Player's motion should be continuous

Screenshot 2022-10-04 at 3 43 18 PM

**Comment by YashIndane** [comment]
Leave it bro! Dont have so much time

**Pull request closed without merging**
