### PR TITLE
Add trail

### PR DESCRIPTION
**Pull request by sparshg**

### CODE REVIEW

**Comment by sparshg** [comment]
I will be busy this week

**Comment by MTM828** [comment]
Oh sorry lol, I haven't been watching this repo. (: /
Yeah I'll be busy this week (dum anoiying examz lol, they've been delayed for like 3 times now) too.
Well anyways, is this for the gravity game?

**Comment by sparshg** [comment]
lol I am also busy with exams, cant do much for now... This PR just adds a trail for now, nothing much

**Comment by MTM828** [comment]
Finally! I'm done with my exams!
I'll be working on the trail now.

**Comment by sparshg** [comment]
Nice to see you back :)

**Comment by MTM828** [comment]
Sorry for the delay, I forgot a bit of Python after that break lol. :P
Here's the code (I only needed to edit planet.py):
```python
import pygame as pg
from constants import *


class Planet:
    def __init__(self, mass, radius, pos=(WIDTH / 2, HEIGHT / 2), vel=(0, 0)):
        self.mass = mass
        self.radius = radius
        self.pos = pg.Vector2(pos)
        self.vel = pg.Vector2(vel)
        self.prevPositions = []

    def calcUpdate(self, planets):
        self.field = pg.Vector2(0, 0)
        for planet in planets:
            r = planet.pos - self.pos
            mag = r.magnitude()
            if mag != 0:
                self.field += G * planet.mass * r * mag ** -3

    def applyUpdate(self, dt):
        self.prevPositions.append((self.pos.x, self.pos.y))
        if len(self.prevPositions) > 100:
            self.prevPositions.pop(0)

        self.vel += self.field * dt
        self.pos += self.vel * dt

    def render(self, surf):
        for i in range(len(self.prevPositions)):
            pg.draw.circle(surf, WHITE, self.prevPositions[len(self.prevPositions) - i - 1], self.radius - i/self.radius)
        pg.draw.circle(surf, WHITE, self.pos, self.radius)
```

**Pull request closed without merging**
